### ISSUE TITLE
Setup with Ruby v3.x doesn't work

### ISSUE THREAD

**Issue by toshimaru** [toshimaru/dotfiles#224]
# Message

```
bundler: failed to load command: serverkit (/Users/runner/work/dotfiles/dotfiles/vendor/bundle/ruby/3.0.0/bin/serverkit)
/Users/runner/work/dotfiles/dotfiles/vendor/bundle/ruby/3.0.0/gems/serverkit-0.7.0/lib/serverkit/actions/base.rb:20:in `initialize': wrong number of arguments (given 1, expected 0) (ArgumentError)
	from /Users/runner/work/dotfiles/dotfiles/vendor/bundle/ruby/3.0.0/gems/serverkit-0.7.0/lib/serverkit/command.rb:84:in `new'
	from /Users/runner/work/dotfiles/dotfiles/vendor/bundle/ruby/3.0.0/gems/serverkit-0.7.0/lib/serverkit/command.rb:84:in `apply'
	from /Users/runner/work/dotfiles/dotfiles/vendor/bundle/ruby/3.0.0/gems/serverkit-0.7.0/lib/serverkit/command.rb:44:in `call'
	from /Users/runner/work/dotfiles/dotfiles/vendor/bundle/ruby/3.0.0/gems/serverkit-0.7.0/bin/serverkit:6:in `<top (required)>'
	from /Users/runner/work/dotfiles/dotfiles/vendor/bundle/ruby/3.0.0/bin/serverkit:25:in `load'
	from /Users/runner/work/dotfiles/dotfiles/vendor/bundle/ruby/3.0.0/bin/serverkit:25:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/cli/exec.rb:58:in `load'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/cli/exec.rb:23:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/cli.rb:4[83](https://github.com/toshimaru/dotfiles/runs/6901552487?check_suite_focus=true#step:3:84):in `exec'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/cli.rb:31:in `dispatch'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor/base.rb:4[85](https://github.com/toshimaru/dotfiles/runs/6901552487?check_suite_focus=true#step:3:86):in `start'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/cli.rb:25:in `start'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/exe/bundle:48:in `block in <top (required)>'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/exe/bundle:36:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.0.0/bin/bundle:23:in `load'
	from /usr/local/lib/ruby/gems/3.0.0/bin/bundle:23:in `<main>'
Error: Process completed with exit code 1.
```

**Comment by toshimaru** [comment]
serverkit now supports Ruby 3.0.

https://github.com/serverkit/serverkit/blob/master/CHANGELOG.md#080
